# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  dockerId: tonyxiang  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: build_env_conda_ubuntu  # Replace with the name of the image you want to publish


steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface
